feat: create code-challenge-i
danimc/dynamic-react-course pull request #3
Opened 2024-12-05 19:59 UTC by bollitodev

First version of the [coding challenge](https://docs.google.com/document/d/1hTD5sBNLtlPQeWKeNyywXESgfWfMCBGJYfG9LXnDizo/edit?tab=t.0)

2024-12-06 17:08 UTC, l-daniel-mora commented on projects/conding-challenge-i/src/App.tsx
> +
Cuando tienes variables que no vas a modificar el valor, la buena practica es declarar `const` 
```suggestion
  const val1 = arr[curr_element]
  const val2 = arr[next_element]

```

2024-12-06 17:15 UTC, l-daniel-mora commented on projects/conding-challenge-i/src/App.tsx
> +  let val2 = arr[next_element]
Cuando los valores de una variable no van a cambiar despues de ser asignado su valor, la buena practica es declararlo con `const` 
```suggestion
  const val1 = arr[curr_element]
  const val2 = arr[next_element]
```

2024-12-06 18:17 UTC, danimc requested changes

2024-12-06 18:17 UTC, danimc commented on projects/conding-challenge-i/src/App.tsx
> +}
estas funciones deberian estar en un custom hook.

Los componentes deberian ser:

lo mas limpios posibles
Pensados con el principio de responsabilidad unica

2024-12-06 18:17 UTC, danimc commented on projects/conding-challenge-i/src/App.tsx
> +  let val2 = arr[next_element]
Cuando el valor no cambia despues de asignado, la buena practica es declarlo como `const`

2024-12-06 18:17 UTC, danimc commented on projects/conding-challenge-i/src/App.tsx
> +  let n = arr.length;
ProTip: Intenta que las variables y constantes tengan nombres significativos, para que sea mas sencillo encontrar "La aguja en el pajar" cuando un sistema crece
```suggestion
  const n = arr.length;
```

2024-12-06 18:17 UTC, danimc commented on projects/conding-challenge-i/src/App.tsx
> +  const maxRange = 10
ProTip: los litereales, o constantes que sirven unicamente como parametros para el calculo de otras funciones, se declaran en mayuscula, y fuera de la funcion del componente, ya que, al no cambiar su valor no es necesario que se regeneren en cada re-renderizado del componente
```suggestion
// Poner esto fuera de funcion App()
  const MINIMUN_RANGE = 1
  const MAXIMUN_RANGE = 10
```

2024-12-06 18:17 UTC, danimc commented on projects/conding-challenge-i/src/App.tsx
> +  }
Esta logica tambien deberia vivir dentro de un customHook

2024-12-06 18:17 UTC, danimc commented on projects/conding-challenge-i/src/App.tsx
> +    setSelectedNameState(closestName)
Quizas, para efectos de utilizar mas elementos de React, podriamos pasar la llamada de esta funcion dentro de un `useEffect`que se mande llamar cada que cambie el `randomNumber`

2024-12-06 18:17 UTC, danimc commented on projects/conding-challenge-i/src/App.tsx
> +            </button>
ProTip: Podrias, con el mismo componente que ya generaste (`CardName`) declarar este bloque.

¿Como?:
Podrias mandar como prop el `variant`o color del que deberia pintarse la caja de texto, pasar un parametro opcional `onClick` para que, si lo tiene, ejecute la accion y si no, no pase nada.

Ventajas:
- Reuzabilidad del componente
- Al ser tecnicamente un componente con el mismo diseño (solo con la diferencia del color) que las `CardName`evitas duplicar la logica y los estilos.
- Muestras conocimiento y adaptabilidad para hacer componentes mas escalables.

2024-12-06 18:17 UTC, danimc commented on projects/conding-challenge-i/src/App.tsx
> +              <CardName name={name} isSelected={index==selectedName}/>
cada que uses `.map` para renderizar dentro de un componente, debes añadirle la prop `key`que debe ser tratada como un indice 'unico y diferente'. 
esto sirve para que react pueda determinar correctamente su estado y comportamiento 

```suggestion
              <CardName key={index} name={name} isSelected={index==selectedName}/>
```

Otra cosa, es mala practica usar el `index`del `map` como la `key` de un elemento. Ya que si un elemento de una lista se "borrara" su `key` pasaria a otro elemento que no le corresponde. intenta usar un indice unico, de preferencia que tenga que ver con el ID del elemento provisto en el objeto.

Para esta prueba no aplica, pero es un proTip

2024-12-06 18:17 UTC, danimc commented on projects/conding-challenge-i/src/App.tsx
> +
```suggestion
// Importaciones de React hasta el Top
import { useState } from 'react'
// Importaciones de librerias de terceros, etc...

// Importacion de componentes y elementos propios del proyecto
import CardName from './components/CardName'

//Importacion de estilos y extras (.css, imagenes, etc...)
import './App.css'


```

Esto es mas un tema de organización de dependencias, solo es una sugerencia para que puedas mantener organizadas tus dependencias y sea mas facil encontrarlas cuando son demasiadas.

2024-12-06 18:17 UTC, danimc commented on projects/conding-challenge-i/src/App.tsx
La logica funciona muy bien :) sinembargo, creo que esta algo compliada incluso para la lectura del codigo.

2024-12-06 18:17 UTC, danimc requested changes
Para pasarlo, pasa la logica a un customHook :)

2024-12-31 03:31 UTC, danimc approved these changes

2024-12-31 03:32 UTC, merged